#!/usr/bin/env bash
#
# Generate target/ca_bundle.h -- the Mozilla/curl root CA bundle embedded as a C
# string -- so the on-target apps can verify real public HTTPS servers instead
# of only the throwaway test CA. Gitignored (like target/test_ca.h).
#
#   scripts/gen-ca-bundle.sh [path-to-cacert.pem]
#
# Source order: explicit arg > the system bundle > download from curl.se.
# Build an app against it with -DCN_CA_BUNDLE=ON (uses kCABundle, VERIFY_REQUIRED).
#
# RAM note: the full bundle (~140 roots, ~230 KB PEM) parses to a few hundred KB
# of live X.509 in RAM. On RAM-tight Macs, hand-trim cacert.pem to just the roots
# you need (e.g. ISRG Root X1 + the CA of your target host) and re-run this.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/target/ca_bundle.h"

PEM=""
if [ "${1:-}" != "" ] && [ -f "$1" ]; then
    PEM="$1"
elif [ -f /etc/ssl/certs/ca-certificates.crt ]; then
    PEM=/etc/ssl/certs/ca-certificates.crt
elif [ -f /etc/pki/tls/certs/ca-bundle.crt ]; then
    PEM=/etc/pki/tls/certs/ca-bundle.crt
else
    PEM="$(mktemp)"
    echo ">> no system bundle; downloading curl.se/ca/cacert.pem ..."
    curl -fsSL https://curl.se/ca/cacert.pem -o "$PEM"
fi

count=$(grep -c "BEGIN CERTIFICATE" "$PEM" || true)
bytes=$(wc -c < "$PEM")
echo ">> source: $PEM ($count roots, $bytes bytes)"

{
    echo "/* generated by scripts/gen-ca-bundle.sh -- Mozilla/curl root CA bundle."
    echo "   $count roots, $bytes bytes of PEM. Do not edit by hand. */"
    echo "static const char kCABundle[] ="
    # one quoted string literal per line; sizeof() includes the trailing NUL,
    # which mbedtls_x509_crt_parse requires for PEM input.
    sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/\r$//' -e 's/^/    "/' -e 's/$/\\n"/' "$PEM"
    echo "    ;"
} > "$OUT"

echo "CA bundle embedded -> $OUT  (build with -DCN_CA_BUNDLE=ON)"
