#!/usr/bin/env bash
#
# Generate a throwaway test PKI for the on-target HTTPS verification demo:
#   deps/test-pki/{ca.pem,ca-key.pem,srv.pem,srv-key.pem}   (gitignored)
#   target/test_ca.h  -- the CA cert embedded as a C string  (gitignored)
#
# The on-target app (built with -DCN_VERIFY=ON) embeds the CA and verifies the
# server cert + hostname. Run a server with the generated cert:
#   openssl s_server -accept 8443 -cert deps/test-pki/srv.pem \
#       -key deps/test-pki/srv-key.pem -www -naccept 100 -no_tls1_3
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PKI="$ROOT/deps/test-pki"
HOST="${1:-localhost}"   # cert CN/SAN; the app verifies against this hostname
mkdir -p "$PKI"

openssl req -x509 -newkey rsa:2048 -nodes -keyout "$PKI/ca-key.pem" -out "$PKI/ca.pem" \
    -days 3650 -subj "/CN=ClassicNet Test CA" >/dev/null 2>&1

openssl req -newkey rsa:2048 -nodes -keyout "$PKI/srv-key.pem" -out "$PKI/srv.csr" \
    -subj "/CN=$HOST" >/dev/null 2>&1
openssl x509 -req -in "$PKI/srv.csr" -CA "$PKI/ca.pem" -CAkey "$PKI/ca-key.pem" \
    -CAcreateserial -days 3650 -extfile <(printf 'subjectAltName=DNS:%s' "$HOST") \
    -out "$PKI/srv.pem" >/dev/null 2>&1

# embed the CA (public) as a C string; sizeof() includes the NUL mbedTLS wants
{
    echo "/* generated by scripts/gen-test-pki.sh -- throwaway test CA */"
    echo "static const char kTestCA[] ="
    sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/^/    "/' -e 's/$/\\n"/' "$PKI/ca.pem"
    echo "    ;"
} > "$ROOT/target/test_ca.h"

echo "test PKI -> $PKI"
echo "CA embedded -> target/test_ca.h  (build cnhttps with -DCN_VERIFY=ON)"
